//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECap.Web.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECap.Web.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string About_E_CAP_En {
            get {
                return ResourceManager.GetString("About_E-CAP_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string About_E_CAP_Jp {
            get {
                return ResourceManager.GetString("About_E-CAP_Jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dfsfdsf.
        /// </summary>
        public static string About_E_CAP_Kr {
            get {
                return ResourceManager.GetString("About_E-CAP_Kr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Confirmation_Email_En {
            get {
                return ResourceManager.GetString("Confirmation_Email_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Confirmation_Email_Jp {
            get {
                return ResourceManager.GetString("Confirmation_Email_Jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Confirmation_Email_Kr {
            get {
                return ResourceManager.GetString("Confirmation_Email_Kr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Contact_En {
            get {
                return ResourceManager.GetString("Contact_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Contact_Jp {
            get {
                return ResourceManager.GetString("Contact_Jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Contact_Kr {
            get {
                return ResourceManager.GetString("Contact_Kr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FAQ_En {
            get {
                return ResourceManager.GetString("FAQ_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FAQ_Jp {
            get {
                return ResourceManager.GetString("FAQ_Jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FAQ_Kr {
            get {
                return ResourceManager.GetString("FAQ_Kr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Help_En {
            get {
                return ResourceManager.GetString("Help_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Help_Jp {
            get {
                return ResourceManager.GetString("Help_Jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Help_Kr {
            get {
                return ResourceManager.GetString("Help_Kr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Help_Page_En {
            get {
                return ResourceManager.GetString("Help_Page_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Help_Page_Jp {
            get {
                return ResourceManager.GetString("Help_Page_Jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Help_Page_Kr {
            get {
                return ResourceManager.GetString("Help_Page_Kr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LinkSample_Question_En {
            get {
                return ResourceManager.GetString("LinkSample_Question_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LinkSample_Question_Jp {
            get {
                return ResourceManager.GetString("LinkSample_Question_Jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LinkSample_Question_Kr {
            get {
                return ResourceManager.GetString("LinkSample_Question_Kr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Login_En {
            get {
                return ResourceManager.GetString("Login_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Login_Imge_En {
            get {
                return ResourceManager.GetString("Login_Imge_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Login_Imge_Jp {
            get {
                return ResourceManager.GetString("Login_Imge_Jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Login_Imge_Kr {
            get {
                return ResourceManager.GetString("Login_Imge_Kr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Login_Jp {
            get {
                return ResourceManager.GetString("Login_Jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Login_Kr {
            get {
                return ResourceManager.GetString("Login_Kr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Password_En {
            get {
                return ResourceManager.GetString("Password_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Password_Jp {
            get {
                return ResourceManager.GetString("Password_Jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Password_Kr {
            get {
                return ResourceManager.GetString("Password_Kr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Pricing_And_Registration_En {
            get {
                return ResourceManager.GetString("Pricing_And_Registration_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Pricing_And_Registration_Jp {
            get {
                return ResourceManager.GetString("Pricing_And_Registration_Jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Pricing_And_Registration_Kr {
            get {
                return ResourceManager.GetString("Pricing_And_Registration_Kr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Privacy_Policy_En {
            get {
                return ResourceManager.GetString("Privacy_Policy_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Privacy_Policy_Jp {
            get {
                return ResourceManager.GetString("Privacy_Policy_Jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Privacy_Policy_Kr {
            get {
                return ResourceManager.GetString("Privacy_Policy_Kr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Sample_Question_Here_En {
            get {
                return ResourceManager.GetString("Sample_Question_Here_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Sample_Question_Here_Jp {
            get {
                return ResourceManager.GetString("Sample_Question_Here_Jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Sample_Question_Here_Kr {
            get {
                return ResourceManager.GetString("Sample_Question_Here_Kr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SampleMessage_En {
            get {
                return ResourceManager.GetString("SampleMessage_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SampleMessage_Jp {
            get {
                return ResourceManager.GetString("SampleMessage_Jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SampleMessage_Kr {
            get {
                return ResourceManager.GetString("SampleMessage_Kr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Services_En {
            get {
                return ResourceManager.GetString("Services_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Services_Jp {
            get {
                return ResourceManager.GetString("Services_Jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Services_Kr {
            get {
                return ResourceManager.GetString("Services_Kr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Sitemap_En {
            get {
                return ResourceManager.GetString("Sitemap_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Sitemap_Jp {
            get {
                return ResourceManager.GetString("Sitemap_Jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Sitemap_Kr {
            get {
                return ResourceManager.GetString("Sitemap_Kr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Taking__The_Test_En {
            get {
                return ResourceManager.GetString("Taking _The_Test_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Taking__The_Test_Jp {
            get {
                return ResourceManager.GetString("Taking _The_Test_Jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Taking__The_Test_Kr {
            get {
                return ResourceManager.GetString("Taking _The_Test_Kr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserID_En {
            get {
                return ResourceManager.GetString("UserID_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserID_Jp {
            get {
                return ResourceManager.GetString("UserID_Jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserID_Kr {
            get {
                return ResourceManager.GetString("UserID_Kr", resourceCulture);
            }
        }
    }
}
